name: Donutgame
version: ${version}
main: com.donutsforlife11.donutgame.Donutgame
bootstrapper: com.donutsforlife11.donutgame.DonutgameBootstrap
description: Donutsforlife11's base for creating minigames
api-version: '26.2'
authors:
  - Donutsforlife11
dependencies:
  server:
    WorldEdit:
      load: BEFORE
      required: true
      join-classpath: true
    ProtocolLib:
      load: BEFORE
      required: false
      join-classpath: true
permissions:
  donutgame.command:
    description: Allows use of Donutgame administrative commands.
    default: op
