name: Donutgame
version: 0.0
main: com.donutsforlife11.donutgame.Donutgame
api: '1.21.11'
api-version: '1.21.11'
description: Donutsforlife11's base for creating minigames
author: Donutsforlife11
depend:
  - WorldEdit
permissions:
  donutgame.command:
    description: Allows use of Donutgame administrative commands.
    default: op
