id: void_wars
main_class: com.donutsforlife11.voidwars.VoidWars
name: Void Wars
maps:
  - classic_enhanced
team_size: 1
team_new_players: true
ground_collapse_time: 15
pvp_enablement_time: 20
base_respawn_time: 20
max_rounds: 3
min_chests: 0
max_chests: 12
protect_regions: true
